### ISSUE TITLE
Tester fails at installing dependencies

### ISSUE THREAD

**Issue by 3ddm3g** [3ddm3g/TheNeighboursRecipeBook#19]
Laravel tester won't install dependencies and will fail at setup scripts.

<img width="888" alt="Screenshot 2022-11-09 at PM 12 34 01" src="https://user-images.githubusercontent.com/42741967/200819893-ed9c08b1-ca2a-4eb4-a583-650ab83efb5b.png">

**Comment by TheHagen98** [comment]
I already fixed it, now I'm looking up the React tests

**Comment by 3ddm3g** [comment]
Alright. Cool!

**Comment by TheHagen98** [comment]
I fixed the react test too, now you can use import too (needed some more configuration and babel dependency)

**Comment by 3ddm3g** [comment]
Awesome! Is it ready to merge then?

**Comment by 3ddm3g** [comment]
[fixed](https://github.com/3ddm3g/TheNeighboursRecipeBook/pull/27)
