### ISSUE TITLE
Tables to be added

### ISSUE THREAD

**Issue by 3ddm3g** [3ddm3g/TheNeighboursRecipeBook#25]
We'll need more tables for storing comments, likes etc. And in tomorrow's meeting we should discuss what kind of data we'd exactly like to have in our app, and how are we going to store them.

Right now 4 tables came into my mind:
- Comments
- Likes
- Messages
- Follows 

These are the most important to have right now so please think about it if we'll need something else and take notes until the meeting. Thank you!

**Comment by 3ddm3g** [comment]
+ Ingredients (will explain in person)

**Comment by rozafaz** [comment]
Comments will contain:
```
user_id
text
post_id
```

Likes will contain:
```
user_id
post_id
```

Messages will contain:

```
sender_id
recepient_id
text
```

Follows will contain:

```
follower
followed
```

Ingredients will contain:

`name`
