### ISSUE TITLE
Creating the Profile component

### ISSUE THREAD

**Issue by rozafaz** [3ddm3g/TheNeighboursRecipeBook#34]
**The planned profile component will include:**

- Displaying posts of the user
1. Grid view
2. List view

- Basic profile data 
1. username
2. bio
3. post count
4. followers
5. following
6. profile picture

To Do:
- [x] #25  needs to be fixed so that we can use the tables for the profile as well.

### Here's also a quick wireframe I did to just get the idea on how the profile page would look:

![wireframe1](https://user-images.githubusercontent.com/80093680/201226028-b99c4a08-d130-4dd2-a54b-a5e3995c232d.png)

![wireframe2](https://user-images.githubusercontent.com/80093680/201226047-1f6a8892-8701-454d-b500-95b2419ef92f.png)

**Comment by rozafaz** [comment]
I made some progress, please check [6a6e2cf](https://github.com/3ddm3g/TheNeighboursRecipeBook/commit/6a6e2cf4a18475e95bf4c1e6ba8ae2b2c9ca404a)

⚠️ Help needed:
function `getPostFromUser` at PostController, not working properly.
If anyone has an idea on how to fix it, please let me know. Until then I will be searching for ways to make it work.

**Comment by 3ddm3g** [comment]
Do you want to fetch every post from a specific user?

**Comment by rozafaz** [comment]
> 

Yes, exactly that.

**Comment by mamutuberalles** [comment]
Hey @rozafaz  I've added the databases, and will gladly help you creating the backend parts of the profile

**Comment by rozafaz** [comment]
Issues solved 761804abb36c20c42b8a4c7eeb253319f4711b4d
