### ISSUE TITLE
React Implementation in develop branch

### ISSUE THREAD

**Issue by mamutuberalles** [3ddm3g/TheNeighboursRecipeBook#7]
Hey guys,

On the 30th of October we should meet and discuss the next step, as well as implementing React into the develop branch, and creating the new features from there.

**Comment by 3ddm3g** [comment]
Alright. What if we'd meet at Roza's place sunday?

**Comment by mamutuberalles** [comment]
That's a brilliant idea, what do you think @TheHagen98

**Comment by rozafaz** [comment]
Hey! A meeting sounds great to discuss and plan thoroughly our next steps.

**Comment by rozafaz** [comment]
Does 3pm work fine with everyone?

**Comment by mamutuberalles** [comment]
Sounds great!

**Comment by rozafaz** [comment]
29386c5
