### ISSUE TITLE
React pages

### ISSUE THREAD

**Issue by mamutuberalles** [3ddm3g/TheNeighboursRecipeBook#8]
Fix the routes, so the React pages are accessible from the browser after the app is launched

**Comment by mamutuberalles** [comment]
We're having a meeting today at 14:00 in the cafeteria

**Comment by mamutuberalles** [comment]
Next steps:
- make the pages that were lost in react
- - Feed
- - Create
- - Edit
- - Full View
- keep the auth pages for later development
- ! only touch the components folder
- after these we can implement backend calls and features

**Comment by 3ddm3g** [comment]
Alright, I'm going to create the `feed` component, along with post view, and list view components. There's going to be a create post button, which will lead to the `Create` page. As `Create` was handed out to @mamutuberalles i'll just leave the button there without functionality, and when you are done working on `Create`, you may link it properly.

**Comment by 3ddm3g** [comment]
I'm closing this and merging back to develop, because this became a frontend all-in branch and i don't want to make it confusing to all of us. Feel free to create separate branches of what you are working on at the moment.
